### Index Now: Home + Updated Pages

POST https://www.bing.com/indexnow
Content-Type: application/json; charset=utf-8

{
  "host": "www.kapresoft.com",
  "key": "{{index-now-key}}",
  "keyLocation": "{{index-now-key-url}}",
  "urlList": [
    "{{site}}/java/2023/11/16/spring-boot-mockmvc-best-practices.html",
    "{{site}}/food/2023/11/16/why-brandy-or-cognac-taste-sweet.html",
    "{{site}}/software/2023/11/09/html-anchor-tags.html",
    "{{site}}"
  ]
}

> {%
    client.test("Success", function() {
        client.assert(response.status === 200, "Not 200")
    })
%}


###
### Index Now Bulk

POST https://www.bing.com/indexnow
Content-Type: application/json; charset=utf-8

{
  "host": "www.kapresoft.com",
  "key": "{{index-now-key}}",
  "keyLocation": "{{index-now-key-url}}",
  "urlList": [
    "{{site}}",
    "{{site}}/java/2023/11/16/spring-boot-mockmvc-best-practices.html",
    "{{site}}/food/2023/11/16/why-brandy-or-cognac-taste-sweet.html",
    "{{site}}/software/2023/11/09/html-anchor-tags.html",
    "{{site}}/software/2023/11/09/rest-hateoas-best-practices.html",
    "{{site}}/software/2023/11/08/rest-api-core-principles.html",
    "{{site}}/software/2023/11/08/rest-content-negotiation-advanced-strategies.html",
    "{{site}}/java/2023/11/07/java-int-vs-integer-best-practices.html",
    "{{site}}/java/2023/11/07/lombok-good-bad-ugly.html",
    "{{site}}/finance/2023/11/06/finance-azul-wells-five-reasons-to-retire.html",
    "{{site}}/java/2023/11/06/java-static-and-default-interface-methods.html",
    "{{site}}/java/2023/11/06/java-concatenating-streams.html",
    "{{site}}/java/2023/11/06/java-modern-collection-utilities.html",
    "{{site}}/java/2023/10/26/java-unit-testing-best-practices.html",
    "{{site}}/software/2023/10/27/strategy-pattern-over-polymorphism.html",
    "{{site}}/food/2023/10/27/pizza-da-michele-naples.html",
    "{{site}}/software/2023/10/27/software-leverage-abstractions.html",
    "{{site}}/java/2023/10/27/java-assertj-vs-hamcrest-assertion.html",
    "{{site}}/java/2023/10/26/java-unit-testing-best-practices.html",
    "{{site}}/software/2023/10/26/agile-story-estimates-and-code-complexity.html",
    "{{site}}/java/2023/10/26/lombok-value-annotation-best-practices.html",
    "{{site}}/java/2023/10/26/lombok-data-annotation-best-practices.html",
    "{{site}}/software/2023/10/25/software-loose-coupling.html",
    "{{site}}/software/2023/10/25/single-responsibility-principle.html",
    "{{site}}/java/2023/10/25/lombok-builder-clean-code.html",
    "{{site}}/music/2023/10/25/is-beyonce-bowing-down-to-taylor-swift.html",
    "{{site}}/java/2023/10/23/factory-design-pattern-best-practices.html",
    "{{site}}/java/2023/10/19/spring-boot-env-specific-profiles.html",
    "{{site}}/java/2023/10/19/spring-devops-profiles-best-practices.html",
    "{{site}}/java/2023/10/19/java-modern-looping-and-filtering.html",
    "{{site}}/java/2023/10/19/java-string-to-list.html",
    "{{site}}/java/2023/10/19/java-parallel-streams.html",
    "{{site}}/java/2023/10/19/springboot-logback.html",
    "{{site}}/java/2023/10/19/logback-for-beginners.html",
    "{{site}}/java/2023/10/18/java-lombok-val-vs-var.html",
    "{{site}}/java/2023/10/18/java-var-best-practices.html",
    "{{site}}/java/2023/10/18/observer-design-pattern.html",
    "{{site}}/java/2023/10/18/factory-design-pattern.html",
    "{{site}}/java/2023/10/17/spring-webflux-reactive-faqs.html",
    "{{site}}/java/2023/10/17/spring-reactive-webclient-combining-calls.html",
    "{{site}}/java/2023/10/17/spring-validation-configuring-global-datetime-format.html",
    "{{site}}/java/2023/10/17/spring-java-bean-validation.html",
    "{{site}}/java/2023/10/17/spring-5-getting-started-with-validation.html",
    "{{site}}/java/2023/10/16/java-uri-vs-url.html",
    "{{site}}/java/2023/10/16/spring-uricomponentsbuilder-best-practices.html",
    "{{site}}/java/2023/10/16/spring6-whats-new-and-migration-guide.html",
    "{{site}}/java/2023/10/02/spring-field-formatting.html",
    "{{site}}/software/2023/10/02/javascript-vs-typescript.html",
    "{{site}}/software/2023/10/02/java-vs-javascript-which-more-demand.html",
    "{{site}}/java/2023/10/01/spring-bean-manipulation-and-beanwrapper.html",
    "{{site}}/java/2023/10/01/spring-controller-vs-restcontroller.html",
    "{{site}}/java/2023/10/01/spring-type-conversion.html",
    "{{site}}/java/2023/10/01/spring-validator-interface.html",
    "{{site}}/java/2023/10/01/spring-validator-resolving-error-codes.html",
    "{{site}}/java/2023/10/01/spring-framework-annotations.html",
    "{{site}}/java/2023/10/01/spring-framework-expression-language.html",
    "{{site}}/java/2023/10/01/spring-boot-conditional-annotations.html",
    "{{site}}/finance/2023/07/18/building-wealth.html",
    "{{site}}/java/2023/06/23/java-cloning-strategies.html",
    "{{site}}/java/2023/06/21/lombok-test-coverage.html",
    "{{site}}/java/2023/06/21/lombok-disadvantages.html",
    "{{site}}/finance/2023/03/13/fdic-what-you-need-to-know.html",
    "{{site}}/finance/2023/03/13/fdic-what-you-need-to-know.html",
    "{{site}}/finance/2023/04/03/bitcoin-environmental-impact.html",
    "{{site}}/finance/2023/04/03/can-bitcoin-be-traced-to-a-person.html",
    "{{site}}/finance/2023/04/03/is-bitcoin-gold-killer.html",
    "{{site}}/finance/2023/04/06/what-is-xrp.html",
    "{{site}}/finance/2023/04/07/los-angeles-ula-tax.html",
    "{{site}}/java/2016/05/15/secure-smtp-with-spring-javamailsender.html",
    "{{site}}/java/2018/08/14/getting-started-with-gradle.html",
    "{{site}}/java/2018/08/15/getting-started-with-java.html",
    "{{site}}/java/2018/08/16/getting-started-with-maven.html",
    "{{site}}/java/2018/08/27/setting-java-compiler-version-in-maven.html",
    "{{site}}/java/2018/09/03/using-apple-keyboard-on-windows-intellij.html",
    "{{site}}/java/2019/04/28/aws-lambda-spring-boot.html",
    "{{site}}/java/2019/05/11/converting-double-value-to-string.html",
    "{{site}}/java/2019/05/11/converting-int-value-to-string.html",
    "{{site}}/java/2019/05/12/using-java-optional.html",
    "{{site}}/java/2019/10/20/aws-lambda-spring-boot-profiles.html",
    "{{site}}/java/2021/11/03/spring-boot-serialize-immutable-objects.html",
    "{{site}}/java/2021/12/27/lombok-builders-and-copy-constructors.html",
    "{{site}}/java/2022/08/29/lombok-cloning-immutable-objects-using-with.html",
    "{{site}}/java/2023/03/13/lombok-exclude-generated-code-from-test-coverage.html",
    "{{site}}/java/2023/03/13/lombok-overview.html",
    "{{site}}/java/2023/03/14/java-17-features.html",
    "{{site}}/java/2023/03/14/java-records.html",
    "{{site}}/java/2023/03/27/java-final-modifier.html",
    "{{site}}/java/2023/03/28/encrypting-property-file-values-with-jasypt.html",
    "{{site}}/java/2023/03/30/how-to-use-constructor-lombok.html",
    "{{site}}/java/2023/03/30/lombok-allargsconstructor-vs-requiredargsconstructor.html",
    "{{site}}/java/2023/03/31/decoupling-domain-objects.html",
    "{{site}}/java/2023/04/04/java-avoid-getters-setters-with-lombok.html",
    "{{site}}/java/2023/04/04/java-virtual-threads.html",
    "{{site}}/java/2023/04/12/spring-boot-jackson-and-lombok-best-practices.html",
    "{{site}}/java/2023/05/01/lombok-singular-annotation.html",
    "{{site}}/java/2023/05/01/maven-vs-gradle.html",
    "{{site}}/java/2023/05/03/java-string-to-map.html",
    "{{site}}/java/2023/05/15/spring-error-handling-best-practices.html",
    "{{site}}/java/2023/05/16/java-vs-kotlin.html",
    "{{site}}/java/2023/05/16/spring-bean-scopes.html",
    "{{site}}/java/2023/05/17/java-comprehensive-guide.html",
    "{{site}}/java/2023/05/17/spring-framework-events.html",
    "{{site}}/java/2023/05/26/spring-shell-aws-cloudfront.html",
    "{{site}}/kitchen/2023/04/06/madein-vs-allclad-stainless-steel-pans.html",
    "{{site}}/kitchen/2023/05/31/smoked-pork-spare-ribs-masterbuilt-1050.html",
    "{{site}}/music/2023/03/31/taylor-vs-beyonce.html",
    "{{site}}/music/2023/05/06/why-taylor-swift-fans-connect.html",
    "{{site}}/music/2023/05/08/taylor-the-eras-tour-watch-without-tickets.html",
    "{{site}}/music/2023/05/13/renaissance-outselling-the-eras-tour.html",
    "{{site}}/music/2023/05/14/why-cities-compete-for-taylor-swift.html",
    "{{site}}/music/2023/05/26/bench-dedicated-to-taylor-swift.html",
    "{{site}}/music/2023/06/02/taylor-swift-most-prolific-artist.html",
    "{{site}}/software/2023/04/13/ten-best-attributes-software-developer.html",
    "{{site}}/software/2023/05/07/cryptography-algorithms-comparison.html",
    "{{site}}/software/2023/05/10/http-status-misunderstandings.html",
    "{{site}}/software/2023/05/11/is-rest-api-stateless.html",
    "{{site}}/software/2023/06/08/singleton-design-pattern.html"
  ]
}

> {%
    client.test("Success", function() {
        client.assert(response.status === 200, "Not 200")
    })
%}

###
### Submit Individual Page

GET https://www.bing.com/indexnow?key={{index-now-key}}&url={{site}}/finance/2023/07/18/building-wealth.html

> {%
    client.test("Success", function() {
        client.assert(response.status === 200, "Not 200")
    })
%}

###
### Check Index Now Key File
# See: https://www.bing.com/indexnow#implementation

GET {{site}}/{{index-now-key}}.txt

> {%
    client.test("Success", function() {
        client.assert(response.status === 200, "Not 200")
    })
%}

###
